### ISSUE TITLE
jQuery overhead

### ISSUE THREAD

**Issue by ideadapt** [bendudler/TS_Snake#2]
https://github.com/bendudler/TS_Snake/blob/e32cf05f324a5b67b3f66dc4ac5d12c5517eab3c/Grid.ts#L12

eigentlich brauchst du hier ja jQuery nicht. so wies am anfang war mit dem native dom api ginge es auch. jquery ist halt etwas eine grosse library, für das was du es hier brauchst. oder hast du jquery just for fun reingenommen :D ?

**Comment by bendudler** [comment]
Primär ging's mal um's ausprobieren :)
